export const listInforProduct = [
  {
    id: "g082asdfu",
    name: "F28004U",
    image: ["/product.jpg", "/product-hide.jpg"],
    category: ["men", "kids", "women", "old"],
    brand: "mota",
    price: 155,
  },
  {
    id: "g082asdlu",
    name: "F28004U",
    image: ["/product.jpg", "/product-hide.jpg"],
    category: ["men", "women"],
    brand: "mota",
    price: 155,
  },
  {
    id: "g082asdfk",
    name: "F28004U",
    image: ["/product.jpg", "/product-hide.jpg"],
    category: ["men"],
    brand: "mota",
    price: 155,
  },
  {
    id: "g082asdfm",
    name: "F28004U",
    image: ["/product.jpg", "/product-hide.jpg"],
    category: ["women"],
    brand: "mota",
    price: 155,
  },
  {
    id: "g082asdfv",
    name: "F28004U",
    image: ["/product.jpg", "/product-hide.jpg"],
    category: ["men", "kids", "women"],
    brand: "mota",
    price: 155,
  },
  {
    id: "g082asdfb",
    name: "F28004U",
    image: ["/product.jpg", "/product-hide.jpg"],
    category: ["men", "kids", "women"],
    brand: "mota",
    price: 155,
  },
  {
    id: "g082asdfaa",
    name: "F28004U",
    image: ["/product.jpg", "/product-hide.jpg"],
    category: ["men", "kids", "women"],
    brand: "mota",
    price: 155,
  },
]